name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y vulkan glfw3 libzip
    - name: make debug
      run: make -j -f Makefile CONF=Debug
    - name: make release
      run: make -j -f Makefile CONF=Release
